n = input('digite um algo:')
print('O tipo primitivo dessa classe é',type(n))
print('Só tem espaços?',n.isspace())
print('É um número?',n.isnumeric())
print('É alfabetico?',n.isalpha())
print('É alfanumérico?',n.isalnum())
print('Está em maiúsculo?',n.isupper())
print('É minúsculo?',n.islower())
print('Está capitalizada?',n.istitle())

